### ISSUE TITLE
Only start and display some features (ala carte)

### ISSUE THREAD

**Issue by Grutli** [jamiegau/cinema-catcher-app#12]
Hello and thanks a lot for your work.

I'm looking for a TMS I can customize quite a lot.

We've got two Dolby IMS3000 with two NAS, mounted as additional storage. Unfortunately it seems there's no TMS (yet?) managing correctly this second storage.

Therefore I only need a few features from cinema-catcher. All the CPL ingests will be managed directly from the IMS.
-  autokdm
- status-monitor and Status Monitor device Control
- Schedule Monitor and KDM Alert

Is it possible to start the containers without samba, aria2server, ftpserver and all the useless (?) stuff ? They cost a lot of resources and use standard ports, that I would like to use for other local services.

Is it also possible to customize the UI, allowing me to only display the features I choose ?

Many thanks for your help !

**Comment by jamiegau** [comment]
Yes, turn of SAMBA aria2server, tp is fine.
sambe makes DCPs available via Samba, 
Aria2server allows pushing of content from the admin.d-cine.net system to a catcher
tp is for remote messaging to the catcher from the server. only works if registered against the admin server.
You can disable these docker containers, but sure if it would generate a heap of error that would make it problematic.  Give it a go.
Without ftpserver, you will not be able to ingest from the catcher if storing DCPs.

Those services shouldnt really take that much resources, they sleep most of the time.  only some memoery would be used.  And memory is cheap and plentiful.

There is no current way to hide parts of the interface.  Maybe in the future.
the player monitoring tool, its a bit alpha and I am not going to do any more work on it until I have time to upgrade the front end framework (As it would be a waist)
The schedule monitor screen too will be delayed until way down the track.

If you only have one screen, you don't really need a TMS.  Just program it directly on the Player.

I am currently working on upgrading the front end framework used for the interface on https://admin.d-cine.net from 
old angularjs to svelte (Do not like React).  It's a big job.  Also extending the tools to use world wide data.  So the schedule viewer will do most regions, not just Australia.

It also will have a universal Certificate download tool and a OpenTDL system that will eventually feed into a free KDM generation manager.  upload a CPL&DKDM and generate KDMs against any vendor certificates.
The universal cert download tool already works.
https://admin.d-cine.net/s1
Uses the same login as for the older interface.

Anyway, once I finish with that, I will hopefully redo the catcher interface too, in to svelte.  It's MUCH faster.
But that's a year away, I would guess, before I start.

**Comment by Grutli** [comment]
Sorry, I just saw your already replied on Github. I'll wait a few years
then :)
If you've got some advices about this damned additional storage I'm always
curious the hear /read.

Thanks
Best regards
Lucas

*Lucas Zibung*
Responsable technique


16, rue du Général-Dufour
1204 Genève
T +41 22 320 78 78
www.cinemas-du-grutli.ch


Le mar. 22 oct. 2024 à 00:37, James Gardiner ***@***.***> a
écrit :

**Comment by Grutli** [comment]
I'll wait a few years then :)
If you've got some advices about this damned additional storage I'm always curious the hear /read.

Thanks
Best regards
