### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by MonziTech** [jamiegau/cinema-catcher-app#2]
Hi, I am installing this app, and all work good. 

Now I have to download the software with the 
_docker compose pull_
command and I receive this response
"_Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml_"

I am in the right dir, there is the right "_docker-compose.yml_" file but the issue remain.

Any idea?

Thank you.

**Comment by jamiegau** [comment]
No idea.  If docker is installed correctly, `docker compose pull` should simply pick up the `docker-compose.yml` if the directory you are currently in.  That's a basic functionality.  You need to work out why that's not working.
you could try
`docker compose -f docker-compose.yml`
To see if that would work, give it the config file specifically.

Did you follow the setup exactly as documented or are you doing this on a different operating system/setup?

**Comment by MonziTech** [comment]
Thanks for the fast answer.
Yes, I follow all your steps in the setup except when I was searching for the Docker install: the system ask me for the install from the Ubuntu 22.04 repo and I follow that way. 
After that the setup was going on well, and I was thinking I found a compatible version.

I will try to use the command in your reply, but maybe I had to reinstall Docker following your command list. 
In this case I have to remove the installed version before reinstall or overwrite the former version?

P.S.: the system I am installing your software on is in my work office and I will not return there until tuesday 11.
Thanks again and have an happy Easter...

**Comment by jamiegau** [comment]
Oh, one warning. you want to avoid the docker that comes with Ubuntu.  It will install a snap version of the container system, and that does not work properly.  Make sure you uninstall docker from Ubuntu completely before installing via the docker website.

If you have the right docker installed, the compose function is now part of docker and you should use
`docker compose`  with a space,
and not
`docker-compose`  with a dash.
