### ISSUE TITLE
Modify "Sent from / reply-to" for emails

### ISSUE THREAD

**Issue by bubbagump24** [jamiegau/cinema-catcher-app#9]
Due to tightened anti-spam policies, many hosting providers block SMTP requests when the from or reply-to domain is different from the domain of the email account. 

Example: 

Domain is my-cinema.com registered with the largest hosting provider in Germany. Email address "catcher@my-cinema.com" is supposed to be used as an SMTP account for sending emails by the cinema-catcher app. 

Trying to do so results in blocked emails. 

`ERROR: Cannot send email to ['XXXXXX'] host:smtp.strato.de port:587 username:catcher@
my-cinema.com use_tls:True : (550, b'5.7.0 Die verwendete Absenderadresse im Mail From: (no_reply@catcher.d-cine.net) gehoert nicht zu Ihrem authentifizierten STRATO Paket. - B-UADOM', 'no_reply@catcher.d-cine.net')`

Translation: 
`The used "sent from" address in Mail From: (no_reply@catcher.d-cine.net) does not belong to the domain authenticated within your STRATO hosting package. - B-UADOM', 'no_reply@catcher.d-cine.net')``

It would be nice if the "from" and "reply to" addressed could be customized and changed from "no_reply@catcher.d-cine.net"  somewhere to avoid this issue. I have tested two more hosting providers and they all block traffic in a similar fashion. 

Gmail no longer supports SMTP:

```
Changes to Gmail syncing with other email clients
To keep your account more secure, Gmail no longer supports third-party apps or devices which require you to share your Google username and password. Sharing your account credentials with third-parties makes it easier for hackers to gain access to your account.

Instead, look for the option to "Sign in with Google," which is a safer way to sync your mail to other apps. [Learn about Sign in with Google](https://support.google.com/accounts/answer/12849458).

Gmail users with a personal Google Account
In June 2024, the option to choose “Enable IMAP” or “Disable IMAP” won't be available. IMAP access is always turned on in Gmail, and your current connections to other email clients aren’t affected. You don’t need to take any action.

Set up Gmail in another email client
To add Gmail to another email client:

On your device, open the client.
Look for an option to "Sign in with Google."
If you need help setting up Gmail in the email client, reach out to the developer.
```

**Comment by jamiegau** [comment]
yes this did occur to me recently too.
And yes, I thought to myself, I need to add a configurable reply-to email.

I'll look at this soon and respond on this when addressed.

**Comment by jamiegau** [comment]
ok,
run in the cinema-catcher-app directory.
`source update.sh`
you should be updated to version 3.4.111 or higher.

This version has the ability to set the from email address when sending email through the configured SMTP server.
Please see if that helps with your problem.

Then get back to me if its all good and I'll close this issue.

**Comment by bubbagump24** [comment]
James, 
Thank you so much for the quick fix. 
Tested successfully!

Cheers from Germany
